[pytest]
pythonpath = .
testpaths = dreamerrl/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
env =
    DREAMER_DETERMINISTIC_TEST=1

# Override PopGym's default --steps=5000
# This forces pytest to use your default instead.
# PopGym's plugin will NOT override this.
addopts = -ra --steps=20

markers =
    rssm: RSSM determinism and CPU/GPU invariants
    smoke: lightweight smoke tests for basic functionality
    functional: functional tests for DreamerV3
    invariants: tests for invariants of the DreamerV3 model
    stress: stress tests for DreamerV3 under extreme conditions
    actor_invariants: tests for invariants of the DreamerV3 actor
    decoder_invariants: tests for invariants of the DreamerV3 decoder
    imagination_invariants: tests for invariants of the DreamerV3 imagination module
    rssm_invariants: tests for invariants of the DreamerV3 RSSM
    manual: tests that are not run by default
    reproducibility: tests for reproducibility of DreamerV3
    popgym: tests for DreamerV3 with PopGym environments
    aux_losses: tests for DreamerV3 auxiliary losses
